---
- name: "Triển khai Keyfile"
  hosts: all
  become: yes
  vars:
    mongodb_port: 27018
    replica_set_name: "rs0"
    php_version: "8.1"
    keyfile_dest: "/etc/mongodb-keyfile"
    mongodb_app_user: "group3_user"
    mongodb_app_pass: "group3_pass"
    mongodb_db: "demo"
    mongodb_collection: "messages"

  tasks:
    - name: "Tạo tệp khóa ngẫu nhiên trên máy Control Node"
      delegate_to: localhost
      become: no
      shell: "openssl rand -base64 756 > templates/mongodb-keyfile"
      args:
        creates: "templates/mongodb-keyfile"
      run_once: true

    - name: "Đẩy Keyfile xuống các node và thiết lập quyền hạn"
      copy:
        src: templates/mongodb-keyfile
        dest: "{{ keyfile_dest }}"
        owner: mongodb
        group: mongodb
        mode: "0600"
      when: "'database_nodes' in group_names or inventory_hostname == 'db-node-backup'"

    - name: "Cập nhật mongod.conf để kích hoạt Security"
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
      when: "'database_nodes' in group_names or inventory_hostname == 'db-node-backup'"
      notify: "Khởi động lại MongoDB"

    - name: "Đảm bảo MongoDB đã nhận cấu hình bảo mật mới"
      meta: flush_handlers

    - name: "Cập nhật index.php với thông tin xác thực mới"
      template:
        src: templates/index.php.j2
        dest: "/var/www/html/index.php"
        owner: www-data
        group: www-data
        mode: "0644"
      when: "'web_servers' in group_names"

    - name: "Khởi động lại PHP-FPM"
      service:
        name: "php{{ php_version }}-fpm"
        state: restarted
      when: "'web_servers' in group_names"
  handlers:
    - name: "Khởi động lại MongoDB"
      service:
        name: mongod
        state: restarted
